### ISSUE TITLE
Import capacitive touch library

### ISSUE THREAD

**Issue by cwalk** [cwalk/CapacitiveTouchLamp#1]
Need to import capacitive touch library that will work with Raspberry Pi.

**Comment by mikestratton** [comment]
Are you using debian for your OS?

**Comment by mikestratton** [comment]
And are you using the MPR121 capacitive touch sensor as your hardware?

**Comment by cwalk** [comment]
Yes, that's what I've decided. Putting it together now.

**Comment by mikestratton** [comment]
I placed a pull request with the hardware reference.

**Comment by cwalk** [comment]
Thanks, but I already had this figured out and handled. Appreciate it though!

**Comment by mikestratton** [comment]
Wow, then why place this as Hacktoberfest? Your wasting my time.
